/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package civitasMVC.GUI;

import civitasMVC.civitas.CasillaCalle;
import civitasMVC.civitas.Jugador;
import java.util.ArrayList;

/**
 *
 * @author esfabiani
 */
public class JugadorPanel extends javax.swing.JPanel {
    
    Jugador jugador;
    
    void setJugador(Jugador newjugador){
        jugador = new Jugador(newjugador);
        jTextField1.setText(jugador.getNombre());
        jTextField2.setText(String.valueOf(jugador.getSaldo()));
        if(jugador.esEspeculador()) jTextField3.setText("True");
        else jTextField3.setText("False");
        rellenaPropiedades(jugador.getPropiedades());
        this.repaint();
        this.revalidate();
    }
    
    private void rellenaPropiedades (ArrayList<CasillaCalle> lista){
        //Se elimina la informacion antigua
        propiedadesPanel.removeAll();
        //Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for (CasillaCalle t : lista) {
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            
            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        //Se fuerza la actualizacion visual del panel de propiedades y del panel del jugador
        repaint();
        revalidate();
    }
    
    /**
     * Creates new form JugadorPanel
     */
    public JugadorPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombre = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Saldo = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        Especulador = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();

        Nombre.setText("Nombre:");
        add(Nombre);

        jTextField1.setEditable(false);
        jTextField1.setText("TextNombre");
        add(jTextField1);

        Saldo.setText("Saldo:");
        add(Saldo);

        jTextField2.setEditable(false);
        jTextField2.setText("TextSaldo");
        add(jTextField2);

        Especulador.setText("Especulador:");
        add(Especulador);

        jTextField3.setEditable(false);
        jTextField3.setText("TextEspec");
        add(jTextField3);

        propiedadesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Especulador;
    private javax.swing.JLabel Nombre;
    private javax.swing.JLabel Saldo;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel propiedadesPanel;
    // End of variables declaration//GEN-END:variables
}
