/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package civitasMVC.GUI;

import civitasMVC.civitas.CasillaCalle;

/**
 *
 * @author esfabiani
 */
public class PropiedadPanel extends javax.swing.JPanel {

    CasillaCalle tituloPropiedad;
    
    void setPropiedad(CasillaCalle propiedad){
        tituloPropiedad = propiedad;
        TextNombre.setText(tituloPropiedad.getNombre());
        TextNCasas.setText(String.valueOf(tituloPropiedad.getNumCasas()));
        TextNHoteles.setText(String.valueOf(tituloPropiedad.getNumHoteles()));
        this.repaint();
    }
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }
    
    public PropiedadPanel(CasillaCalle calle){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        NCasas = new javax.swing.JLabel();
        NHoteles = new javax.swing.JLabel();
        TextNombre = new javax.swing.JTextField();
        TextNCasas = new javax.swing.JTextField();
        TextNHoteles = new javax.swing.JTextField();

        nombre.setText("Nombre:");

        NCasas.setText("n* de casas:");

        NHoteles.setText("n* de hoteles:");

        TextNombre.setEditable(false);
        TextNombre.setText("TextNombre");

        TextNCasas.setEditable(false);
        TextNCasas.setText("TextNCasas");

        TextNHoteles.setEditable(false);
        TextNHoteles.setText("TextNHoteles");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre)
                    .addComponent(NCasas)
                    .addComponent(NHoteles))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextNCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre)
                    .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NCasas)
                    .addComponent(TextNCasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NHoteles)
                    .addComponent(TextNHoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NCasas;
    private javax.swing.JLabel NHoteles;
    private javax.swing.JTextField TextNCasas;
    private javax.swing.JTextField TextNHoteles;
    private javax.swing.JTextField TextNombre;
    private javax.swing.JLabel nombre;
    // End of variables declaration//GEN-END:variables
}
